Demo.NTI.Portal/Demo.NTI.Portal/Controllers/RoleManagementController.cs
using Demo.NTI.BLL.ViewModel;
using Demo.NTI.DAL.Extend;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace Demo.NTI.Portal.Controllers
{

    [Authorize(Roles = "Admin")]
    public class RoleManagementController : Controller
    {


        private readonly RoleManager<ApplicationRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public RoleManagementController(RoleManager<ApplicationRole> roleManager , UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }


        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var roles = await roleManager.Roles.ToListAsync();
            return View(roles);
        }


        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(ApplicationRole role)
        {

          
            role.CreatedBy = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var result = await roleManager.CreateAsync(role);

            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }

            return View(role);
        }

        [HttpGet]
        public async Task<IActionResult> AddOrRemoveUser(string RoleId)
        {


            var role = await roleManager.FindByIdAsync(RoleId);

            var model = new List<UserInRoleVM>();

            foreach (var user in userManager.Users)
            {
                var userInRole = new UserInRoleVM()
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userInRole.IsSelected = true;
                }
                else
                {
                    userInRole.IsSelected = false;
                }

                model.Add(userInRole);
            }

            return View(model);

        }



        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUser(List<UserInRoleVM> model, string RoleId)
        {
            var role = await roleManager.FindByIdAsync(RoleId);

            for (int i = 0; i < model.Count; i++)
            {

                var user = await userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result;

                if (model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {

                    result = await userManager.AddToRoleAsync(user, role.Name);
                }

                if (!model[i].IsSelected && (await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
            }

            return RedirectToAction("Index");
        }


    }
}

Demo.NTI.Portal/Demo.NTI.Portal/Views/RoleManagement/AddOrRemoveUser.cshtml
@model List<UserInRoleVM>


@{
    ViewData["Title"] = "Add Or Remove Users";
}

<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Roles Management</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Manage Role</a></li>
                        <li class="breadcrumb-item active">Add Or Remove Users</li>

                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>


    <section class="content">
        <div class="container-fluid">


            <form method="post" class="form-group">

                <div class="card-header">
                    <h2>Add Or Remove User In Role</h2>
                </div>


                @for (int i = 0; i < Model.Count; i++)
                {
                    <input asp-for="@Model[i].IsSelected" type="checkbox" class="filled-in">
                    <label asp-for="@Model[i].IsSelected">@Model[i].UserName</label>

                    <input type="hidden" asp-for="@Model[i].UserId" />
                    <input type="hidden" asp-for="@Model[i].UserName" />
                    <br />
                }

                <div class="card-footer">
                    <input type="submit" value="Assign" class="btn btn-primary" />
                </div>

            </form>

            <a asp-controller="RoleManagement" asp-action="Index">Cancle</a>

        </div>
    </section>

</div>

Demo.NTI.Portal/Demo.NTI.Portal/Views/RoleManagement/Create.cshtml
@model ApplicationRole


@{
    ViewData["Title"] = "Roles";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Roles</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Roles</li>

                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">

                <form asp-controller="RoleManagement" asp-action="Create" method="post" class="form-group">


                    <div asp-validation-summary="All" class="text-danger" ></div>

                    <label asp-for="Name">Role Name</label>
                    <input type="text" asp-for="Name" class="form-control" />
                    <br />

                    <center>
                        <input type="submit" value="save" class="btn btn-primary" />
                        <input type="reset" value="cancle" class="btn btn-primary" />
                    </center>


                </form>

            </div>
        </div>
    </section>
    <!-- /.content -->
</div>




@section JqueryValidation{
    <script src="~/plugins/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/plugins/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Demo.NTI.Portal/Demo.NTI.Portal/Views/RoleManagement/Index.cshtml
@model IEnumerable<ApplicationRole>
@{
    ViewData["Title"] = "roles";
}

<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Roles Management</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Manage Role</a></li>
                        <li class="breadcrumb-item active">Roles</li>

                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>


    <section class="content">
        <div class="container-fluid">




            <div class="row">

                <a asp-controller="RoleManagement" asp-action="Create" class="btn btn-primary">Create New Role</a>

                <table class="table table-hover table-striped table-bordered text-center">
                    <thead class="thead-dark">
                        <tr>
                            <th>Role Name</th>
                            <th>Is Active</th>
                            <th>Created On</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Name</td>
                                <td>@item.IsActive</td>
                                <td>@item.CreatedAt</td>
                                <td>
                                    <div class="dropdown">
                                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Actions</button>
                                        <div class="dropdown-menu">
                                            <a asp-controller="RoleManagement" asp-action="Update" asp-route-id="@item.Id" class="dropdown-item">Update</a>
                                            <a asp-controller="RoleManagement" asp-action="Delete" asp-route-id="@item.Id" class="dropdown-item">Delete</a>
                                            <a asp-controller="RoleManagement" asp-action="Details" asp-route-id="@item.Id" class="dropdown-item">Details</a>
                                            <a asp-controller="RoleManagement" asp-action="AddOrRemoveUser" asp-route-RoleId="@item.Id" class="dropdown-item">Add/Remove Users</a>

                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </section>

</div>